recursive: true
reporter: "spec"
retries: 0
slow: 20
timeout: 2000
ui: "bdd"
# for more options see here https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
require: '@babel/register'
